server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: asd6168003
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 8.130.70.222
    port: 6379
    password: asd6168003
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

